### ISSUE TITLE
What video game(s) are you proud of making?

### ISSUE THREAD

**Issue by dannyfritz** [jackrugile/ama#2]

**Comment by jackrugile** [comment]
To be honest, I'm not proud of any of my games. I'm proud of parts and components of them, but none of them as a whole. All of my games thus far have been such short term projects that I didn't get to fully explore an idea and commit to making it a _real_ game. I'm hoping to upgrade the duration/size of my game projects and start committing 3-6 months at least, rather than a weekend or a week. Just need to commit to an idea. Easier said than done ;)

I don't want to be a complete downer though, so here are some parts of games that I've made that I am proud of:

## Radius Raid

![radius2](https://cloud.githubusercontent.com/assets/726153/19507908/2143bb4c-9593-11e6-9b0a-d0f30030f32d.gif)

I am proud of this one because I realized how much fun stuff you can cram in a tiny size (13k zipped). It was a [js13kGames](http://js13kgames.com) competition submission and I was able to include sound, particles, different enemy behaviors, a minimap, and persistent stats. Code golf + game dev are a perfect match.

**[Play Radius Raid](https://jackrugile.com/radius-raid)**

## Elematter

![elematter1](https://cloud.githubusercontent.com/assets/726153/19508144/c56dbd7a-9594-11e6-905a-e7726c0bff56.gif)

Elematter was a lot of fun to make because I got take on the challenge of moving objects along a path, balancing difficulty between the baddies and towers, and controlling the scale of time. Also, I'm proud that I was able to discover how powerful pure DOM can be as a game renderer.

**[Play Elematter](https://jackrugile.com/elematter)**

## Mono Move

![mono-move1](https://cloud.githubusercontent.com/assets/726153/19508472/b217a81a-9596-11e6-8929-968d5920a70b.gif)

I'm proud of Mono Move because I got to explore the aesthetic style that I'd like to apply to a full game. I'm ok with the fact that I am not creating highly detailed characters or art in my games. I want to commit to a more minimal geometric style, with a strong emphasis on color and light. This game had some performance issues, but it was a fun project.

**[Play Mono Move (Chrome Recommended)](https://jackrugile.com/mono-move)**

## Itch A Skitch

![itchaskitch1](https://cloud.githubusercontent.com/assets/726153/19508744/17c35bd6-9598-11e6-842e-d8e368d07b76.gif)

Not exactly a game, but I'm proud of Itch A Skitch because I was able to recreate something from my childhood. I tried to match some of the quirks and visuals of the physical toy. This project is also special to me because it persists user created content.

**[Play Itch A Skitch](http://itchaskitch.com)**

**Comment by dannyfritz** [comment]
Glad I asked. These are pretty sweet. 👍

**Comment by jackrugile** [comment]
Thanks @dannyfritz :) I need to try some of your games too!
