### ISSUE TITLE
Answer me, these questions three...

### ISSUE THREAD

**Issue by Teagan42** [jackrugile/ama#4]
1. What is your name?
2. What is your quest?
3. What is the air speed velocity of a laden swallow?

**Comment by jackrugile** [comment]
I don't know that!

![vlijiz](https://cloud.githubusercontent.com/assets/726153/19833885/4f97c87e-9e0f-11e6-8b85-b136e298c8c2.gif)

I've been avoiding this question because it means I have to admit publicly that I've never seen any Monty Python movies. I quite enjoyed the clips I watched in research for this question though.

Shame away...
